services:
  php:
    image: yiisoftware/yii2-php:7.4-apache
    environment:
      - PHP_ENABLE_XDEBUG=1
    volumes:
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      - ./:/app:delegated
    ports:
      - '8000:80'
    extra_hosts:
      - "host.docker.internal:host-gateway"
    # user: "1000:1000"

  db:
    image: mysql:latest
    volumes:
    #  - ./db_data:/var/lib/mysql
      - ./docker/initdb.d:/docker-entrypoint-initdb.d
    ports:
      - '33060:3306'
    environment:
      MYSQL_ROOT_PASSWORD: test
      # MYSQL_DATABASE: test
      MYSQL_USER: test
      MYSQL_PASSWORD: test
